test_that("download status table should show file sizes", {
  js_file = system.file("htmljs", "animint.js", package="animint2")
  js_text = paste(readLines(js_file), collapse=" ")
  mb_column = grep('attr\\("class", "MB"\\)', js_text)
  expect_gt(length(mb_column), 0)
  files_column = grep('attr\\("class", "files"\\)', js_text)
  expect_gt(length(files_column), 0)
  rows_column = grep('attr\\("class", "rows"\\)', js_text)
  expect_gt(length(rows_column), 0)
})
