---
title: "My Rmd Document"
output: 
  html_document:
    self_contained: false
---
  
```{r safety, echo = FALSE}
library(knitr)
# Calling knit_meta() here is just a safety protocol.
# knit_print.animint uses knitr's meta-data to efficiently place JS scripts.
# If this meta-data isn't clear when a document is knit, the result won't be rendered properly
knit_meta() 
```
  
  
```{r plot-1-top}
library(animint2)
dat <- data.frame(x = 1:10, y = 1:10, label = rep(c("a178", "b934"), 5))
animint(q = ggplot()+geom_point(aes(
  x, y,
  tooltip = paste("tooltip in first plot", x),
  colour = label),
  data = dat,
  help="first plot")+
  scale_x_continuous("first plot with color legend"))
```

Clicking on the plot above should not affect the plot below.

```{r plot.1.bottom}
animint(q = qplot(
  x, y, data = dat, colour = label,
  help="second plot",
  xlab = "second plot with color legend"))
```

The plot below has no interactive features.

```{r boring}
animint(q = qplot(rnorm(100), xlab = "non-interactive plot"))
```

The next data viz consists of two plots, one of which should have
common chunk data files. 

```{r breakpoints}
data(breakpoints)
only.error <- subset(breakpoints$error,type=="E")
only.segments <- subset(only.error,bases.per.probe==bases.per.probe[1])
signal.colors <- c(estimate="#0adb0a",
                   latent="#0098ef")
animint(
  signal=ggplot()+
    geom_point(aes(position, signal), showSelected="bases.per.probe",
               data=breakpoints$signals)+
    geom_label_aligned(aes(
      position, signal, label=position),
      color=signal.colors[["latent"]],
      data=breakpoints$imprecision,
      alignment="horizontal")+
    geom_line(aes(position, signal), colour=signal.colors[["latent"]],
              data=breakpoints$imprecision)+
    geom_segment(aes(first.base, mean, xend=last.base, yend=mean),
                 showSelected=c("segments", "bases.per.probe"),
                 colour=signal.colors[["estimate"]],
                 data=breakpoints$segments)+
    geom_vline(aes(xintercept=base),
               showSelected=c("segments", "bases.per.probe"),
               colour=signal.colors[["estimate"]],
               linetype="dashed",
               data=breakpoints$breaks),
  error=ggplot()+
    geom_vline(aes(
      xintercept=segments,
      id=paste0("select_segments_",segments)),
      clickSelects="segments",
      data=only.segments, lwd=17, alpha=1/2)+
    geom_line(aes(segments, error, group=bases.per.probe),
              clickSelects="bases.per.probe",
              data=only.error, lwd=4),
  signalUP=ggplot()+
    theme_animint(update_axes="y")+
    geom_point(aes(position, signal), showSelected="bases.per.probe",
               data=breakpoints$signals),
  first=list(segments=6))
```
